# Generated by Django 5.1.5 on 2025-03-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_order_order_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
    ]
