# Generated by Django 5.1.5 on 2025-03-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_image_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Персональная скидка'),
        ),
    ]
