# Generated by Django 5.1.5 on 2025-03-27 05:50

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_personal_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='images',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='core.image', verbose_name='Картинки'),
        ),
    ]
