# Generated by Django 5.1.5 on 2025-04-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_image_alter_good_discount_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='admin',
        ),
    ]
